# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='femicidio',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='femicidio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
